/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static java.awt.PageAttributes.MediaType.D;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mode.ListStudent;
import mode.Student;
import mode.Tinh;

/**
 *
 * @author Cloudy
 */
public class View_StudentManager extends javax.swing.JFrame {
    ListStudent listStudent;
    ButtonGroup buttonGroup;

    /**
     * Creates new form View_StudentManager
     */
    public View_StudentManager(ListStudent lst) {
        this.listStudent = lst;
        initComponents();
        someThing();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void someThing(){
        buttonGroup = new ButtonGroup();
        buttonGroup.add(jRadioButton_Nam);
        buttonGroup.add(jRadioButton_Nu);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_QueQuan1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField_MaThiSinh_Tim = new javax.swing.JTextField();
        button_tim = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField_MaThiSinh = new javax.swing.JTextField();
        jTextField_HoVaTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_NgaySinh = new javax.swing.JTextField();
        jComboBox_QueQuan2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton_Nam = new javax.swing.JRadioButton();
        jRadioButton_Nu = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_Mon1 = new javax.swing.JTextField();
        jTextField_Mon2 = new javax.swing.JTextField();
        jTextField_Mon3 = new javax.swing.JTextField();
        jButtonHuyBo = new javax.swing.JButton();
        jButtonLuu = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Quê Quán");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 40));

        jComboBox_QueQuan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang",
            "Bà Rịa – Vũng Tàu",
            "Bạc Liêu",
            "Bắc Giang",
            "Bắc Kạn",
            "Bắc Ninh",
            "Bến Tre",
            "Bình Dương",
            "Bình Định",
            "Bình Phước",
            "Bình Thuận",
            "Cà Mau",
            "Cao Bằng",
            "Cần Thơ",
            "Đà Nẵng",
            "Đắk Lắk",
            "Đắk Nông",
            "Điện Biên",
            "Đồng Nai",
            "Đồng Tháp",
            "Gia Lai",
            "Hà Giang",
            "Hà Nam",
            "Hà Nội",
            "Hà Tĩnh",
            "Hải Dương",
            "Hải Phòng",
            "Hậu Giang",
            "Hòa Bình",
            "Thành phố Hồ Chí Minh",
            "Hưng Yên",
            "Khánh Hòa",
            "Kiên Giang",
            "Kon Tum",
            "Lai Châu",
            "Lạng Sơn",
            "Lào Cai",
            "Lâm Đồng",
            "Long An",
            "Nam Định",
            "Nghệ An",
            "Ninh Bình",
            "Ninh Thuận",
            "Phú Thọ",
            "Phú Yên",
            "Quảng Bình",
            "Quảng Nam",
            "Quảng Ngãi",
            "Quảng Ninh",
            "Quảng Trị",
            "Sóc Trăng",
            "Sơn La",
            "Tây Ninh",
            "Thái Bình",
            "Thái Nguyên",
            "Thanh Hóa",
            "Thừa Thiên Huế",
            "Tiền Giang",
            "Trà Vinh",
            "Tuyên Quang",
            "Vĩnh Long",
            "Vĩnh Phúc",
            "Yên Bái"}));
getContentPane().add(jComboBox_QueQuan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 220, 30));

jLabel2.setText("Mã Thí Sinh");
getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 40));
getContentPane().add(jTextField_MaThiSinh_Tim, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 200, 30));

button_tim.setText("Tìm");
button_tim.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_timActionPerformed(evt);
    }
    });
    getContentPane().add(button_tim, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, 40));
    getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 880, 10));

    jLabel3.setText("Danh Sách Thí Sinh");
    jLabel3.setPreferredSize(new java.awt.Dimension(150, 16));
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 40));

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Mã Thí Sinh", "Họ Tên", "Quê Quán", "Ngay Sinh", "Giới tính", "Điểm 1", "Điểm 2", "Điểm 3"
        }
    ));
    jScrollPane1.setViewportView(jTable1);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 890, 300));
    getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 880, 10));

    jTextField_MaThiSinh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField_MaThiSinhActionPerformed(evt);
        }
    });
    getContentPane().add(jTextField_MaThiSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 170, 30));
    getContentPane().add(jTextField_HoVaTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 170, 30));

    jLabel4.setText("Thông Tin Thí Sinh");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, 30));
    getContentPane().add(jTextField_NgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 170, 30));

    jComboBox_QueQuan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang",
        "Bà Rịa – Vũng Tàu",
        "Bạc Liêu",
        "Bắc Giang",
        "Bắc Kạn",
        "Bắc Ninh",
        "Bến Tre",
        "Bình Dương",
        "Bình Định",
        "Bình Phước",
        "Bình Thuận",
        "Cà Mau",
        "Cao Bằng",
        "Cần Thơ",
        "Đà Nẵng",
        "Đắk Lắk",
        "Đắk Nông",
        "Điện Biên",
        "Đồng Nai",
        "Đồng Tháp",
        "Gia Lai",
        "Hà Giang",
        "Hà Nam",
        "Hà Nội",
        "Hà Tĩnh",
        "Hải Dương",
        "Hải Phòng",
        "Hậu Giang",
        "Hòa Bình",
        "Thành phố Hồ Chí Minh",
        "Hưng Yên",
        "Khánh Hòa",
        "Kiên Giang",
        "Kon Tum",
        "Lai Châu",
        "Lạng Sơn",
        "Lào Cai",
        "Lâm Đồng",
        "Long An",
        "Nam Định",
        "Nghệ An",
        "Ninh Bình",
        "Ninh Thuận",
        "Phú Thọ",
        "Phú Yên",
        "Quảng Bình",
        "Quảng Nam",
        "Quảng Ngãi",
        "Quảng Ninh",
        "Quảng Trị",
        "Sóc Trăng",
        "Sơn La",
        "Tây Ninh",
        "Thái Bình",
        "Thái Nguyên",
        "Thanh Hóa",
        "Thừa Thiên Huế",
        "Tiền Giang",
        "Trà Vinh",
        "Tuyên Quang",
        "Vĩnh Long",
        "Vĩnh Phúc",
        "Yên Bái" }));
jComboBox_QueQuan2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
    jComboBox_QueQuan2ActionPerformed(evt);
    }
    });
    getContentPane().add(jComboBox_QueQuan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 170, 30));

    jLabel5.setText("Mã Thí Sinh");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

    jLabel6.setText("Họ Và Tên");
    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

    jLabel7.setText("Quê Quán");
    getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

    jLabel8.setText("Ngày Sinh");
    getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 60, -1));

    jLabel9.setText("Giới Tinh");
    getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, 30));

    jRadioButton_Nam.setText("Nam");
    jRadioButton_Nam.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioButton_NamActionPerformed(evt);
        }
    });
    getContentPane().add(jRadioButton_Nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 80, -1));

    jRadioButton_Nu.setText("Nữ");
    jRadioButton_Nu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioButton_NuActionPerformed(evt);
        }
    });
    getContentPane().add(jRadioButton_Nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 100, -1));

    jLabel10.setText("Môn 1");
    getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, 10));

    jLabel11.setText("Môn 2");
    getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, -1, 10));

    jLabel12.setText("Môn 2");
    getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, -1, -1));
    getContentPane().add(jTextField_Mon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 230, 30));

    jTextField_Mon2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField_Mon2ActionPerformed(evt);
        }
    });
    getContentPane().add(jTextField_Mon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 230, 30));
    getContentPane().add(jTextField_Mon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, 230, 30));

    jButtonHuyBo.setText("Hủy Bỏ");
    jButtonHuyBo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonHuyBoActionPerformed(evt);
        }
    });
    getContentPane().add(jButtonHuyBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 660, 120, 40));

    jButtonLuu.setText("Lưu");
    jButtonLuu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonLuuActionPerformed(evt);
        }
    });
    getContentPane().add(jButtonLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 660, 120, 40));

    jButtonThem.setText("Thêm");
    jButtonThem.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonThemActionPerformed(evt);
        }
    });
    getContentPane().add(jButtonThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 150, 40));

    jButtonXoa.setText("Xóa");
    jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonXoaActionPerformed(evt);
        }
    });
    getContentPane().add(jButtonXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, 120, 40));

    jButtonSua.setText("Sửa");
    jButtonSua.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonSuaActionPerformed(evt);
        }
    });
    getContentPane().add(jButtonSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 120, 40));

    jMenu2.setText("About");

    About.setText("About me");
    About.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            AboutActionPerformed(evt);
        }
    });
    jMenu2.add(About);

    jMenuBar1.add(jMenu2);

    jMenu1.setText("File");

    jMenuItem1.setText("Open");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem1ActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItem1);

    jMenuItem2.setText("Save");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem2ActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItem2);

    jMenuItem3.setText("Exit");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem3ActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItem3);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            this.openFile();
            for(Student student : this.listStudent){
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
           model.addRow(new Object[]{student.getMaThiSinh()+"",student.getTenThiSinh(),student.getQueQuan().getTenTinh()
           ,student.getNgaySinh().toString(),student.isGioiTinh()?"Nam":"Nu",student.getDiemMon1()+"",student.getDiemMon2()+"",student.getDiemMon3()+""});
           
            }
        } catch (IOException ex) {
            Logger.getLogger(View_StudentManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(View_StudentManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Ban có muốn thoat khoi chuong trinh khong ?");
        if(choice==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jTextField_MaThiSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MaThiSinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MaThiSinhActionPerformed

    private void jComboBox_QueQuan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_QueQuan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_QueQuan2ActionPerformed

    private void jRadioButton_NuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_NuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_NuActionPerformed

    private void jRadioButton_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_NamActionPerformed

    private void jTextField_Mon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Mon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Mon2ActionPerformed

    private void jButtonHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyBoActionPerformed
        // TODO add your handling code here:
        this.clearText();
    }//GEN-LAST:event_jButtonHuyBoActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        clearText();
     listStudent.setChoice("Them");
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuuActionPerformed
       if(this.listStudent.getChoice().equals("Them")||this.listStudent.getChoice().equals("")){          
           Student student = getStudent();
           this.listStudent.add(student);
           SimpleDateFormat time = new SimpleDateFormat("dd/MM/YYYY");
            String times = time.format(student.getNgaySinh());
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
           model.addRow(new Object[]{student.getMaThiSinh()+"",student.getTenThiSinh(),student.getQueQuan().getTenTinh()
           ,times,student.isGioiTinh()?"Nam":"Nu",student.getDiemMon1()+"",student.getDiemMon2()+"",student.getDiemMon3()+""});
           
           JOptionPane.showMessageDialog(this,
    "Luu thanh cong.");
           System.out.println(student.toString());
           
           clearText();
       }else if(this.listStudent.getChoice().equals("Sua")){
            int selectedRow =  jTable1.getSelectedRow();
            Student student = this.getStudent();
            
            //sua lai student
            this.listStudent.get(selectedRow).setMaThiSinh(student.getMaThiSinh());
            this.listStudent.get(selectedRow).setTenThiSinh(student.getTenThiSinh());
            this.listStudent.get(selectedRow).setGioiTinh(student.isGioiTinh());
            this.listStudent.get(selectedRow).setNgaySinh(student.getNgaySinh());
            this.listStudent.get(selectedRow).setQueQuan(student.getQueQuan());
            this.listStudent.get(selectedRow).setDiemMon1(student.getDiemMon1());
            this.listStudent.get(selectedRow).setDiemMon2(student.getDiemMon2());
            this.listStudent.get(selectedRow).setDiemMon3(student.getDiemMon3());
            
            SimpleDateFormat time = new SimpleDateFormat("dd/MM/YYYY");
            String times = time.format(student.getNgaySinh());
            //
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setValueAt(student.getMaThiSinh(), selectedRow, 0);
            model.setValueAt(student.getTenThiSinh(), selectedRow, 1);
            model.setValueAt(student.getQueQuan().getTenTinh(), selectedRow, 2);
            model.setValueAt(student.isGioiTinh()?"Nam":"Nu", selectedRow, 4);
            model.setValueAt(times, selectedRow, 3);
            model.setValueAt(student.getDiemMon1(), selectedRow, 5);
            model.setValueAt(student.getDiemMon2(), selectedRow, 6);
            model.setValueAt(student.getDiemMon3(), selectedRow, 7);
            
            System.err.println("Sua xong");
            
       }
    }//GEN-LAST:event_jButtonLuuActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        this.listStudent.setChoice("Sua");
      int selectedRow =  jTable1.getSelectedRow();
        
    Student student =  this.listStudent.get(selectedRow);
    jTextField_MaThiSinh.setText(student.getMaThiSinh()+"");
        jTextField_HoVaTen.setText(student.getTenThiSinh());
        jTextField_Mon1.setText(student.getDiemMon1()+"");
     jTextField_Mon2.setText(student.getDiemMon2()+"");
     jTextField_Mon3.setText(student.getDiemMon3()+"");
     jTextField_NgaySinh.setText(student.getNgaySinh().toString());
     int que = student.getQueQuan().getMaTinh();
     jComboBox_QueQuan2.setSelectedIndex(que);
     if(student.isGioiTinh()){
         jRadioButton_Nam.setSelected(true);
     }else{
         jRadioButton_Nu.setSelected(true);
     }
        
    
     //
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        
        int choice = JOptionPane.showConfirmDialog(this, "Ban có muốn xóa không ?");
        if(choice==JOptionPane.YES_OPTION){
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(selectedRow);
            this.listStudent.remove(selectedRow);
        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void button_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_timActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jTextField_MaThiSinh_Tim.getText().trim());
        int tinhx = jComboBox_QueQuan1.getSelectedIndex();
        Tinh tinh = Tinh.getTinhById(tinhx);

        
        ArrayList<String> s = new ArrayList();
        
        for(Student student : this.listStudent){
            if(student.getMaThiSinh()==id && student.getQueQuan().equals(tinh)){
            s.add(student.toString()+"\n");
            }
        }
        
         JOptionPane.showMessageDialog( null,s);
        
    }//GEN-LAST:event_button_timActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Phan mem quan ly Sinh vien \n By:Dang Trung Huy");
    }//GEN-LAST:event_AboutActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            this.listStudent.saveFile();
        } catch (IOException ex) {
            Logger.getLogger(View_StudentManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void openFile() throws FileNotFoundException, IOException, ClassNotFoundException {
        FileInputStream fis = new FileInputStream("D:\\code\\java\\studentManager\\Student.txt");
        ObjectInputStream ois = new ObjectInputStream(fis);
        this.listStudent = (ListStudent) ois.readObject();
        ois.close();
    }

    
    
    
    public void clearText(){
        jTextField_MaThiSinh.setText("");
        jTextField_HoVaTen.setText("");
     jTextField_Mon1.setText("");
     jTextField_Mon2.setText("");
     jTextField_Mon3.setText("");
     jTextField_NgaySinh.setText("");    
     buttonGroup.clearSelection();
     jComboBox_QueQuan2.setSelectedIndex(-1);
    }
    public  Student getStudent(){
        int maSinhvien = Integer.parseInt(jTextField_MaThiSinh.getText().trim());
        String hoTen = jTextField_HoVaTen.getText();
        int tinhx = jComboBox_QueQuan2.getSelectedIndex();
        Tinh tinh = Tinh.getTinhById(tinhx);
        Date date = new Date(jTextField_NgaySinh.getText());
        boolean sex = false;
        if(jRadioButton_Nam.isSelected()){
            sex = true;
        }else if(jRadioButton_Nu.isSelected()){
             sex = false;
        }
        float diem1 = Float.parseFloat(jTextField_Mon1.getText().trim());
        float diem2 = Float.parseFloat(jTextField_Mon2.getText().trim());
        float diem3 = Float.parseFloat(jTextField_Mon3.getText().trim());
        
        
        Student student = new Student(maSinhvien,hoTen,tinh,date,sex,diem1,diem2,diem3);
        
      return student;
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton button_tim;
    private javax.swing.JButton jButtonHuyBo;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JComboBox<String> jComboBox_QueQuan1;
    private javax.swing.JComboBox<String> jComboBox_QueQuan2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButton jRadioButton_Nam;
    private javax.swing.JRadioButton jRadioButton_Nu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_HoVaTen;
    private javax.swing.JTextField jTextField_MaThiSinh;
    private javax.swing.JTextField jTextField_MaThiSinh_Tim;
    private javax.swing.JTextField jTextField_Mon1;
    private javax.swing.JTextField jTextField_Mon2;
    private javax.swing.JTextField jTextField_Mon3;
    private javax.swing.JTextField jTextField_NgaySinh;
    // End of variables declaration//GEN-END:variables
}
